const SmokeModes = (function () {
  const order = ['textSmoke', 'realistic', 'artistic'];
  let current = order[0];

  const presets = {
    realistic: {
      key: 'realistic',
      name: 'Realistic',
      renderStyle: 'particles',
      colors: [
        'rgba(210,216,224,',
        'rgba(190,196,206,',
        'rgba(168,174,184,',
        'rgba(225,228,234,',
      ],
      lightColor: 'rgba(255,240,218,',
      startAlpha: 0.07,
      maxAlpha: 0.24,
      startSize: 4,
      maxSize: 48,
      speed: { min: 0.3, max: 0.8 },
      lifetime: { min: 8000, max: 16000 },
      drift: 0.15,
      swirlStrength: 0,
      swirlFrequency: 0,
      maxParticles: 4320,
      exhaleMultiplier: 7,
      emitRate: 8,
      emissions: {
        fingertip: {
          count: 4,
          spreadX: 1.8,
          spreadY: 1.2,
          velocityX: 0.07,
          velocityY: { min: -1.55, max: -0.82 },
          lifeMultiplier: 1.28,
          sizeMultiplier: 0.5,
          alphaMultiplier: 0.5,
          turbulence: 0.14,
          riseAccel: 0.0026,
          drag: 0.992,
          lateralDamping: 0.965,
          trailWidth: 1.15,
          trailAlpha: 0.42,
          strandiness: 0.94,
          unravel: 0.92,
          curlStrength: 0.12,
          spreadAccel: 0.08,
          fadeInEnd: 0.14,
          fadeOutStart: 0.42,
          fadeOutPower: 1.6,
          spriteAlphaMultiplier: 0.16,
          spriteFadeStart: 0.1,
          spriteFadePower: 2.1,
          veilAlphaMultiplier: 0.42,
          veilScale: 1.9,
          haloAlphaMultiplier: 0.06,
          haloScale: 2.45,
          trailSoftness: 3.4,
          lightAlphaMultiplier: 0.24,
          lightScale: 2.2,
          lightOffsetX: -0.2,
          lightOffsetY: -0.3,
          dissolveStartDistance: 110,
          dissolveEndDistance: 360,
          dissolvePower: 1.62,
        },
        exhaleBurst: {
          count: 112,
          spreadX: 66,
          spreadY: 26,
          velocityX: 2.7,
          velocityY: { min: -2.8, max: -0.95 },
          lifeMultiplier: 1.8,
          sizeMultiplier: 1.22,
          alphaMultiplier: 0.82,
          turbulence: 1.42,
          riseAccel: 0.0048,
          drag: 0.993,
          lateralDamping: 0.962,
          trailWidth: 2.8,
          trailAlpha: 0.18,
          strandiness: 0.46,
          unravel: 0.7,
          curlStrength: 0.24,
          spreadAccel: 0.08,
          fadeInEnd: 0.1,
          fadeOutStart: 0.5,
          fadeOutPower: 1.32,
          trailSoftness: 2.4,
          lightAlphaMultiplier: 0.16,
          lightScale: 1.8,
          lightOffsetX: -0.12,
          lightOffsetY: -0.2,
          dissolveStartDistance: 720,
          dissolveEndDistance: 1580,
          dissolvePower: 1.06,
        },
        exhaleStream: {
          count: 68,
          spreadX: 46,
          spreadY: 18,
          velocityX: 1.25,
          velocityY: { min: -2.0, max: -0.65 },
          lifeMultiplier: 1.7,
          sizeMultiplier: 0.98,
          alphaMultiplier: 0.72,
          turbulence: 1.05,
          riseAccel: 0.004,
          drag: 0.992,
          lateralDamping: 0.948,
          trailWidth: 2.2,
          trailAlpha: 0.24,
          strandiness: 0.66,
          unravel: 0.82,
          curlStrength: 0.12,
          spreadAccel: 0.42,
          fadeInEnd: 0.14,
          fadeOutStart: 0.5,
          fadeOutPower: 1.38,
          trailSoftness: 2.8,
          lightAlphaMultiplier: 0.18,
          lightScale: 1.9,
          lightOffsetX: -0.14,
          lightOffsetY: -0.22,
          dissolveStartDistance: 660,
          dissolveEndDistance: 1450,
          dissolvePower: 1.08,
        },
      },
      ember: {
        coreRadius: 4.2,
        haloRadius: 14,
        sparkRadius: 1.1,
        coreAlpha: 0.92,
        haloAlpha: 0.26,
        sparkAlpha: 0.8,
      },
    },
    artistic: {
      key: 'artistic',
      name: 'Artistic',
      renderStyle: 'particles',
      colors: [
        'rgba(0,255,255,',
        'rgba(255,0,255,',
        'rgba(128,0,255,',
        'rgba(255,100,200,',
      ],
      startAlpha: 0.2,
      maxAlpha: 0.4,
      startSize: 6,
      maxSize: 90,
      speed: { min: 0.6, max: 1.5 },
      lifetime: { min: 3500, max: 7000 },
      drift: 0.5,
      swirlStrength: 2.5,
      swirlFrequency: 0.003,
      maxParticles: 300,
      exhaleMultiplier: 6,
      emitRate: 8,
      emissions: {
        fingertip: {
          count: 4,
          spreadX: 5,
          spreadY: 3,
          velocityX: 0.3,
          velocityY: { min: -1.9, max: -1.0 },
          lifeMultiplier: 1.34,
          sizeMultiplier: 0.62,
          alphaMultiplier: 0.64,
          turbulence: 0.42,
          riseAccel: 0.003,
          drag: 0.992,
          lateralDamping: 0.938,
          trailWidth: 2.4,
          trailAlpha: 0.46,
          strandiness: 0.98,
          unravel: 1,
          curlStrength: 0.4,
          spreadAccel: 0.42,
          fadeOutStart: 0.4,
          fadeOutPower: 1.7,
          dissolveStartDistance: 78,
          dissolveEndDistance: 220,
          dissolvePower: 1.86,
        },
        exhaleBurst: {
          count: 56,
          spreadX: 64,
          spreadY: 24,
          velocityX: 2.5,
          velocityY: { min: -2.5, max: -0.7 },
          lifeMultiplier: 1.38,
          sizeMultiplier: 1.56,
          alphaMultiplier: 1.26,
          turbulence: 1.55,
          riseAccel: 0.0039,
          drag: 0.993,
          lateralDamping: 0.968,
          trailWidth: 4,
          trailAlpha: 0.22,
          strandiness: 0.42,
          unravel: 0.6,
          curlStrength: 0.18,
          spreadAccel: 0.2,
          fadeOutStart: 0.46,
          fadeOutPower: 1.28,
          dissolveStartDistance: 122,
          dissolveEndDistance: 336,
          dissolvePower: 1.2,
        },
        exhaleStream: {
          count: 32,
          spreadX: 42,
          spreadY: 18,
          velocityX: 1.2,
          velocityY: { min: -1.6, max: -0.5 },
          lifeMultiplier: 1.18,
          sizeMultiplier: 1.2,
          alphaMultiplier: 1.08,
          turbulence: 1.2,
          riseAccel: 0.0029,
          drag: 0.99,
          lateralDamping: 0.96,
          trailWidth: 3.1,
          trailAlpha: 0.26,
          strandiness: 0.56,
          unravel: 0.7,
          curlStrength: 0.24,
          spreadAccel: 0.28,
          fadeOutStart: 0.48,
          fadeOutPower: 1.36,
          dissolveStartDistance: 104,
          dissolveEndDistance: 286,
          dissolvePower: 1.28,
        },
      },
      ember: {
        coreRadius: 5.1,
        haloRadius: 18,
        sparkRadius: 1.5,
        coreAlpha: 1,
        haloAlpha: 0.35,
        sparkAlpha: 0.92,
      },
    },
    textSmoke: {
      key: 'textSmoke',
      name: 'Text Smoke',
      renderStyle: 'text-smoke',
      colors: ['rgba(228,228,236,', 'rgba(206,210,218,', 'rgba(184,188,200,'],
      lightColor: 'rgba(255,245,232,',
      startAlpha: 0.12,
      maxAlpha: 0.86,
      startSize: 12,
      maxSize: 32,
      speed: { min: 0.35, max: 1.1 },
      lifetime: { min: 2200, max: 5200 },
      drift: 0.28,
      swirlStrength: 0,
      swirlFrequency: 0,
      maxParticles: 0,
      exhaleMultiplier: 1,
      emitRate: 7,
      textFontFamily: "'Pretendard', 'Apple SD Gothic Neo', 'Noto Sans KR', sans-serif",
      textPhrases: ['시발 또 야근', '존나 빡친다', '퇴사가 답이다', '에라 모르겠다', '못 해먹겠다', '담타나 가자', '내가 왜 사냐', '현타 온다 진짜', '월급 루팡 중', '다 때려치워', '회의 또 회의', '칼퇴 마렵다', '됐고 집에 간다', '나 좀 살자', '보고서 좆까', '될 대로 돼라'],
      textStyles: {
        fingertip: { fontSize: 9, alpha: 0.085, maxTokens: 10 },
        inhaling: { fontSize: 10, alpha: 0.105, maxTokens: 8 },
        burst: { fontSize: 27, alpha: 0.78, maxTokens: 8 },
        stream: { fontSize: 21, alpha: 0.46, maxTokens: 12 },
      },
      emissions: {
        fingertip: { count: 1, spreadX: 3, spreadY: 5, velocityX: 0.08, velocityY: { min: -1.0, max: -0.46 } },
        exhaleBurst: { count: 2, spreadX: 28, spreadY: 16, velocityX: 1.6, velocityY: { min: -1.3, max: -0.3 } },
        exhaleStream: { count: 1, spreadX: 24, spreadY: 14, velocityX: 1.2, velocityY: { min: -1.1, max: -0.25 } },
      },
      ember: {
        coreRadius: 4.2,
        haloRadius: 14,
        sparkRadius: 1.1,
        coreAlpha: 0.92,
        haloAlpha: 0.26,
        sparkAlpha: 0.8,
      },
    },
  };

  function get() {
    return presets[current];
  }

  function toggle() {
    const currentIndex = order.indexOf(current);
    current = order[(currentIndex + 1) % order.length];
    return presets[current];
  }

  function getName() {
    return presets[current].name;
  }

  return { get, toggle, getName };
})();
