const SmokeModes = (function () {
  let current = 'realistic';

  const presets = {
    realistic: {
      name: 'Realistic',
      colors: [
        'rgba(210,216,224,',
        'rgba(190,196,206,',
        'rgba(168,174,184,',
        'rgba(225,228,234,',
      ],
      lightColor: 'rgba(255,240,218,',
      startAlpha: 0.07,
      maxAlpha: 0.24,
      startSize: 4,
      maxSize: 48,
      speed: { min: 0.3, max: 0.8 },
      lifetime: { min: 8000, max: 16000 },
      drift: 0.15,
      swirlStrength: 0,
      swirlFrequency: 0,
      maxParticles: 4320,
      exhaleMultiplier: 7,
      emitRate: 8,
      emissions: {
        fingertip: {
          count: 16,
          spreadX: 3,
          spreadY: 1.5,
          velocityX: 0.12,
          velocityY: { min: -1.6, max: -0.82 },
          lifeMultiplier: 2.15,
          sizeMultiplier: 0.48,
          alphaMultiplier: 0.76,
          turbulence: 0.22,
          riseAccel: 0.0038,
          drag: 0.995,
          lateralDamping: 0.93,
          trailWidth: 1.8,
          trailAlpha: 0.56,
          strandiness: 0.98,
          unravel: 1.1,
          curlStrength: 0.42,
          spreadAccel: 0.38,
          fadeInEnd: 0.18,
          fadeOutStart: 0.58,
          fadeOutPower: 1.3,
          spriteAlphaMultiplier: 0.18,
          spriteFadeStart: 0.08,
          spriteFadePower: 2.2,
          veilAlphaMultiplier: 0.44,
          veilScale: 2.2,
          haloAlphaMultiplier: 0.08,
          haloScale: 2.8,
          trailSoftness: 4,
          lightAlphaMultiplier: 0.32,
          lightScale: 2.6,
          lightOffsetX: -0.22,
          lightOffsetY: -0.32,
          dissolveStartDistance: 620,
          dissolveEndDistance: 1420,
          dissolvePower: 1.12,
        },
        exhaleBurst: {
          count: 136,
          spreadX: 60,
          spreadY: 24,
          velocityX: 4.0,
          velocityY: { min: -3.9, max: -1.35 },
          lifeMultiplier: 2.0,
          sizeMultiplier: 1.4,
          alphaMultiplier: 1.25,
          turbulence: 1.15,
          riseAccel: 0.0039,
          drag: 0.994,
          lateralDamping: 0.968,
          trailWidth: 3.2,
          trailAlpha: 0.24,
          strandiness: 0.42,
          unravel: 0.55,
          curlStrength: 0.18,
          spreadAccel: 0.18,
          fadeInEnd: 0.1,
          fadeOutStart: 0.54,
          fadeOutPower: 1.2,
          trailSoftness: 2.4,
          lightAlphaMultiplier: 0.22,
          lightScale: 2.0,
          lightOffsetX: -0.12,
          lightOffsetY: -0.2,
          dissolveStartDistance: 640,
          dissolveEndDistance: 1480,
          dissolvePower: 1.04,
        },
        exhaleStream: {
          count: 80,
          spreadX: 40,
          spreadY: 16,
          velocityX: 1.6,
          velocityY: { min: -2.55, max: -0.96 },
          lifeMultiplier: 1.8,
          sizeMultiplier: 1.1,
          alphaMultiplier: 1.0,
          turbulence: 0.78,
          riseAccel: 0.0032,
          drag: 0.993,
          lateralDamping: 0.955,
          trailWidth: 2.4,
          trailAlpha: 0.32,
          strandiness: 0.62,
          unravel: 0.72,
          curlStrength: 0.24,
          spreadAccel: 0.28,
          fadeInEnd: 0.14,
          fadeOutStart: 0.52,
          fadeOutPower: 1.3,
          trailSoftness: 2.8,
          lightAlphaMultiplier: 0.26,
          lightScale: 2.2,
          lightOffsetX: -0.14,
          lightOffsetY: -0.22,
          dissolveStartDistance: 600,
          dissolveEndDistance: 1320,
          dissolvePower: 1.08,
        },
      },
      ember: {
        coreRadius: 4.2,
        haloRadius: 14,
        sparkRadius: 1.1,
        coreAlpha: 0.92,
        haloAlpha: 0.26,
        sparkAlpha: 0.8,
      },
    },
    artistic: {
      name: 'Artistic',
      colors: [
        'rgba(0,255,255,',
        'rgba(255,0,255,',
        'rgba(128,0,255,',
        'rgba(255,100,200,',
      ],
      startAlpha: 0.2,
      maxAlpha: 0.4,
      startSize: 6,
      maxSize: 90,
      speed: { min: 0.6, max: 1.5 },
      lifetime: { min: 3500, max: 7000 },
      drift: 0.5,
      swirlStrength: 2.5,
      swirlFrequency: 0.003,
      maxParticles: 300,
      exhaleMultiplier: 6,
      emitRate: 8,
      emissions: {
        fingertip: {
          count: 4,
          spreadX: 5,
          spreadY: 3,
          velocityX: 0.3,
          velocityY: { min: -1.9, max: -1.0 },
          lifeMultiplier: 1.34,
          sizeMultiplier: 0.62,
          alphaMultiplier: 0.64,
          turbulence: 0.42,
          riseAccel: 0.003,
          drag: 0.992,
          lateralDamping: 0.938,
          trailWidth: 2.4,
          trailAlpha: 0.46,
          strandiness: 0.98,
          unravel: 1,
          curlStrength: 0.4,
          spreadAccel: 0.42,
          fadeOutStart: 0.4,
          fadeOutPower: 1.7,
          dissolveStartDistance: 78,
          dissolveEndDistance: 220,
          dissolvePower: 1.86,
        },
        exhaleBurst: {
          count: 42,
          spreadX: 64,
          spreadY: 24,
          velocityX: 4.1,
          velocityY: { min: -4, max: -1.15 },
          lifeMultiplier: 1.38,
          sizeMultiplier: 1.56,
          alphaMultiplier: 1.26,
          turbulence: 1.55,
          riseAccel: 0.0039,
          drag: 0.993,
          lateralDamping: 0.968,
          trailWidth: 4,
          trailAlpha: 0.22,
          strandiness: 0.42,
          unravel: 0.6,
          curlStrength: 0.18,
          spreadAccel: 0.2,
          fadeOutStart: 0.46,
          fadeOutPower: 1.28,
          dissolveStartDistance: 122,
          dissolveEndDistance: 336,
          dissolvePower: 1.2,
        },
        exhaleStream: {
          count: 22,
          spreadX: 42,
          spreadY: 18,
          velocityX: 1.9,
          velocityY: { min: -2.5, max: -0.82 },
          lifeMultiplier: 1.18,
          sizeMultiplier: 1.2,
          alphaMultiplier: 1.08,
          turbulence: 1.2,
          riseAccel: 0.0029,
          drag: 0.99,
          lateralDamping: 0.96,
          trailWidth: 3.1,
          trailAlpha: 0.26,
          strandiness: 0.56,
          unravel: 0.7,
          curlStrength: 0.24,
          spreadAccel: 0.28,
          fadeOutStart: 0.48,
          fadeOutPower: 1.36,
          dissolveStartDistance: 104,
          dissolveEndDistance: 286,
          dissolvePower: 1.28,
        },
      },
      ember: {
        coreRadius: 5.1,
        haloRadius: 18,
        sparkRadius: 1.5,
        coreAlpha: 1,
        haloAlpha: 0.35,
        sparkAlpha: 0.92,
      },
    },
  };

  function get() {
    return presets[current];
  }

  function toggle() {
    current = current === 'realistic' ? 'artistic' : 'realistic';
    return presets[current];
  }

  function getName() {
    return presets[current].name;
  }

  return { get, toggle, getName };
})();
